# Generated by Django 5.0 on 2023-12-22 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='interest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SIS.interest'),
        ),
    ]
