# Generated by Django 5.0 on 2023-12-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIS', '0003_student_email_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='female', max_length=10),
        ),
    ]
