# Generated by Django 5.0 on 2023-12-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIS', '0004_student_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='graduation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
